export type Movie = {
    adult: boolean,
    genre_ids: number[],
    id: number,
    original_language: string,
    original_title: string,
    overview: string,
    poster_path: string,
    release_date: string,
    title: string,
    video: boolean,
    vote_average: number,
    vote_count: number,
    popularity: number,
    character: string,
    credit_id: number,
    order: number,
    media_type: string,
}